[build]
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "20"

# Use Next.js adapter for proper App Router support
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
