[build]
  command = "npm run build && cp public/manifest.json .next/"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
